### ISSUE TITLE
Add Python2 for the hooks

### ISSUE THREAD

**Issue by LapinFou** [clamy54/docker-svn-iF.SVNAdmin#1]
Hi,

First of all, thanks a lot for your SVN docker. I'm currently using DSM6 on my Synology NAS.
I'm planning to migrate to DSM7, however I'm must first migrate all my SVN repos to Docker.

In my current setup, I'm using a lot of Hooks written in Python 2.
Would it be possible to include Python 2 in your next release ?

**Comment by clamy54** [comment]
Done !

**Comment by LapinFou** [comment]
Wahoouuu !
That was very very fast!
Thanks. 🤩👍

I should have mention that the command is
apt install python  (it is not python2). 
Maybe you could also add python3?
It would also be nice to add a path for the hooks folder.
Maybe /hooks or /var/hooks?
Or a more generic path such as /var/scripts ?!?

Again, thanks a lot for this container!
👍👍👍

**Comment by LapinFou** [comment]
Fantastic!
I saw your updates. I will give a try tomorrow.

**Comment by LapinFou** [comment]
I tested the latest version.
Hooks, Python[2|3] and timezone are now OK.
Thanks a lot.
From all the searches have done, your docker container is the best solution to replace the Synology SVN package. 👍👍
Easy to setup and work perfectly on both DSM6 and DSM7.
There is still a small issue. I will open a new ticket.
