### ISSUE TITLE
[Synology NAS] Opening the Terminal tab will crash the container

### ISSUE THREAD

**Issue by LapinFou** [clamy54/docker-svn-iF.SVNAdmin#3]
When opening the Terminal tab from the Docker GUI (Synology DSM) will crash the container.
Maybe some env variables are missing?
If I wait the container auto-restart, then I will be able to open a Bash terminal.
For the record, the original version (before adding Python) had also this issue.

The snapshots are in French.

Here is the crash:
![image](https://user-images.githubusercontent.com/1685030/152507106-69e2b49d-4a72-451a-a4c0-18e7961acfd6.png)

After waiting the container restart, then I can open a Terminal:
![image](https://user-images.githubusercontent.com/1685030/152507936-a002a6ab-5740-4efb-8328-cde12acf519e.png)

Last point, you didn't update the instructions here: https://registry.hub.docker.com/r/clamy54/svn-svnadmin/

Thanks again for taking the time to add all those enhancements.

**[EDIT]** I've done some Google and some tries, however I've not been able to find a solution.
I really don't know why there is this kind of problem.

**Comment by clamy54** [comment]
This is a known issue on synology with many containers. The official httpd container also have this issue. A more optimal way to gain shell access is to use ssh & docker CLI. Another workaround is to install portainer to manage containers. Portainer allow shell access throught web ui and works very well on synology.

**Comment by LapinFou** [comment]
@clamy54 
I tried your latest release.
Everything is absolutely perfect. 🤩
Thanks a lot. Your container is now the perfect solution to replace the Synology DSM6 SVN package.
All your config are clean and professional.
I hope your container will become very popular. 🤞

Concerning the Terminal access, thanks a lot for your tips. I may try Portainer.
However, since I used only some basic containers, it may be a bit overkill for my setup.
At first I will dig the ssh/CLI solution.

**Comment by LapinFou** [comment]
OK, I tried the CLI through a SSH session on my Syno.
`docker exec -it svnadmin /bin/bash`
This does perfectly the job.
Since, from now, your container is perfect, I will not have a big usage of it.

I had a look on Portainer. It looks very nice, but it is definitely overkill for my usage.
Again, thanks for your time and support.
