### ISSUE TITLE
Apache Warnings

### ISSUE THREAD

**Issue by LapinFou** [clamy54/docker-svn-iF.SVNAdmin#4]
I know the following warnings are harmless, however here is a solution to remove them.

- `AH00558`: **apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message**

 This one is easy to fix. I never created a docker container, but the following command in the [Dockerfile](https://github.com/clamy54/docker-svn-iF.SVNAdmin/blob/main/Dockerfile) file should be OK.
`RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf`

- `AH01574`: **module dav_module is already loaded, skipping**
This one arises because both `authz_svn.load` and `dav_svn.load` refers to `dav.load`
```
grep mod_dav /etc/apache2/mods-enabled/*
/etc/apache2/mods-enabled/authz_svn.load:<IfModule !mod_dav_svn.c>
/etc/apache2/mods-enabled/dav.load:LoadModule dav_module /usr/lib/apache2/modules/mod_dav.so
/etc/apache2/mods-enabled/dav_svn.load:<IfModule !mod_dav_svn.c>
/etc/apache2/mods-enabled/dav_svn.load:    <IfModule !mod_dav.c>
/etc/apache2/mods-enabled/dav_svn.load:    LoadModule dav_svn_module /usr/lib/apache2/modules/mod_dav_svn.so
```
To fix this warning, the `dav.load` must be changed from that
```
LoadModule dav_module /usr/lib/apache2/modules/mod_dav.so
```
to that
```
<IfModule !mod_dav.c>
    LoadModule dav_module /usr/lib/apache2/modules/mod_dav.so
</IfModule>
```

Done! 😁
Clean log, no more warnings.

**Comment by clamy54** [comment]
Fixed
